# Generated by Django 5.2.4 on 2025-07-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='annata',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='wine',
            name='cantina',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='regione',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='varietà',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wine',
            name='voto_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wine',
            name='voto_totale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
